config/routes.rb
Rails.application.routes.draw do
	
	
	
	devise_for :users, controllers: {registrations: 'users/registrations'}
	resources :users do
		resourc :profile
	end
	resources :contacts
	
	root 'pages#index'
	
	get 'home' => 'pages#home'
	
	get 'service' => 'pages#service'
	
	get 'about' => 'pages#about'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, presence: true
	validates :email, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  attr_accessor :stripe_card_token
  
  def save_with_payment
	  if valid?
		  customer = Stripe::Customer.create(description: email, plan: plan_id, source: stripe_card_token)
		  self.stripe_customer_token = customer.id
		  save!
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  	def configure_permitted_parameters
	  	devise_parameter_sanitizer.for(:sign_up){|u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation)}
	  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end
	
	def create
		@contact = Contact.new(contact_params)
		
		if @contact.save
			name = params[:contact][:name]
			email = params[:contact][:email]
			body = params[:contact][:comments]
			ContactMailer.contact_email(name, email, body).deliver
			
			
			flash[:success] = "Message sent."
			redirect_to new_contact_path
		else
			flash[:danger] = "Error occured, message has not been sent."
			redirect_to new_contact_path
		end
	end
	
	private
		def contact_params
			params.require(:contact).permit(:name, :email, :comments)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
	  @basic_plan = Plan.find(1)
	  @pro_plan = Plan.find(2)
  end

  def home
  end

  def service
  end

  def about
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	before_filter :select_plan, only: :new
	
	def create
		super do |resource|
			if params[:plan]
				resource.plan_id = params[:plan]
				if resource.plan_id == 2
					resource.save_with_payment
				else
					resource.save
				end
			end
		end
	end
	
	private
	def select_plan
		unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2')
			flash[:notice] = "Please select a membership plan to sign up."
			redirect_to root_url
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aritcles_helper.rb
module AritclesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/contacts/new.html.erb
<!-- <div class="container" style="margin-top: 30px"> -->
	<div class="row">
		<div class="col-sm-4 col-sm-offset-4">
			<h2>Contact Me</h2>
			<div class="well">
				<%= form_for @contact do |f| %>
					<div class="form-group">
						<%= f.label :name %>
						<%= f.text_field :name, class: 'form-control' %>
					</div>
					
					<div class="form-group">
						<%= f.label :email %>
						<%= f.email_field :email, class: 'form-control' %>
					</div>
					
					<div class="form-group">
						<%= f.label :comments %>
						<%= f.text_area :comments, class: 'form-control' %>
					</div>
					
					<%= f.submit 'Submit' ,class: 'btn btn-default' %>
				<% end %>
			</div>
		</div>
	</div>
<!-- </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'https://js.stripe.com/v2/', type: 'text/javascript' %>
  <%= javascript_include_tag 'application' %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse" role="navigation" style="margin-bottom: 0px">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "SoloConflict" , root_path, class: "navbar-brand" %>
		</div>
	
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav">
				<li><%= link_to "About", about_path %> </li>
				<li><%= link_to "Home", home_path %></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Service <b class="caret"></b></a>
					<ul class="dropdown-menu" role="menu">
						<li><% link_to "Music" %></li>
						<li><a href="#">Another action</a></li>
						<li><a href="#">Something else here</a></li>
						<li><a href="#">Separated link</a></li>
						<li><a href="#">One more separated link</a></li>
					</ul>
				</li>
			</ul>
			
			
			<form class="navbar-form navbar-right" role="search">				
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Search">
				</div>
				<button type="submit" class="btn btn-default">Submit</button>
			</form>
			
			<div class="nav navbar-nav navbar-right">
				<% if current_user %>
					<%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-default navbar-btn' %>
				<% else %>
					<%= link_to "Log In", new_user_session_path, class: 'btn btn-default navbar-btn', method: :get %>
				<% end %>
			</div>

		</div><!-- /.navbar-collapse -->
	</nav>


	<% flash.each do |key, value| %>
		<%= content_tag :div, value, class: "alert alert-#{key}" %>
	<% end %>
	
	
	<%= yield %>



	<footer class="footer">
		<div class="container">
			<ul>
				<li><%= link_to "&copy He-Chun Chang", about_path %> </li>
				<li><%= link_to "Contact ME", new_contact_path %> </li>
				<li><%= icon 'facebook-official' %></li>
				<li><i class="fa fa-spotify"></i></li>
				<li><i class="fa fa-twitter-square"></i></li>
			</ul>
		</div>
	</footer>
</body>
</html>

app/views/pages/about.html.erb
<div class="container" style="margin-top: 30px">
	<article>
		<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, aliquet vel, dapibus id, mattis vel, nisi. Sed pretium, ligula sollicitudin laoreet viverra, tortor libero sodales leo, eget blandit nunc tortor eu nibh. Nullam mollis. Ut justo. Suspendisse potenti.</p>
		
		<p>Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing, commodo quis, gravida id, est. Sed lectus. Praesent elementum hendrerit tortor. Sed semper lorem at felis. Vestibulum volutpat, lacus a ultrices sagittis, mi neque euismod dui, eu pulvinar nunc sapien ornare nisl. Phasellus pede arcu, dapibus eu, fermentum et, dapibus sed, urna.</p>
		
		<p>Morbi interdum mollis sapien. Sed ac risus. Phasellus lacinia, magna a ullamcorper laoreet, lectus arcu pulvinar risus, vitae facilisis libero dolor a purus. Sed vel lacus. Mauris nibh felis, adipiscing varius, adipiscing in, lacinia vel, tellus. Suspendisse ac urna. Etiam pellentesque mauris ut lectus. Nunc tellus ante, mattis eget, gravida vitae, ultricies ac, leo. Integer leo pede, ornare a, lacinia eu, vulputate vel, nisl.</p>
		
		<p>Suspendisse mauris. Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula. Integer adipiscing risus a sem. Nullam quis massa sit amet nibh viverra malesuada. Nunc sem lacus, accumsan quis, faucibus non, congue vel, arcu. Ut scelerisque hendrerit tellus. Integer sagittis. Vivamus a mauris eget arcu gravida tristique. Nunc iaculis mi in ante. Vivamus imperdiet nibh feugiat est.</p>
		
		<p>Ut convallis, sem sit amet interdum consectetuer, odio augue aliquam leo, nec dapibus tortor nibh sed augue. Integer eu magna sit amet metus fermentum posuere. Morbi sit amet nulla sed dolor elementum imperdiet. Quisque fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque adipiscing eros ut libero. Ut condimentum mi vel tellus. Suspendisse laoreet. Fusce ut est sed dolor gravida convallis. Morbi vitae ante. Vivamus ultrices luctus nunc. Suspendisse et dolor. Etiam dignissim. Proin malesuada adipiscing lacus. Donec metus. Curabitur gravida.</p>
	</article>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/index.html.erb
    <header id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for Slides -->
        <div class="carousel-inner">
            <div class="item active">
                <!-- Set the first background image using inline CSS below. -->
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide One');"></div>
                <div class="carousel-caption">
                    <h2>Caption 1</h2>
                </div>
            </div>
            <div class="item">
                <!-- Set the second background image using inline CSS below. -->
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Two');"></div>
                <div class="carousel-caption">
                    <h2>Caption 2</h2>
                </div>
            </div>
            <div class="item">
                <!-- Set the third background image using inline CSS below. -->
                <div class="fill" style="background-image:url('http://placehold.it/1900x1080&text=Slide Three');"></div>
                <div class="carousel-caption">
                    <h2>Caption 3</h2>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>

    </header>
    
    <div class="row" style="margin: 30px">
    	<div class="col-sm-6">
    		<div class="well text-center">
    			<h2>Basic Membership</h2>
    			<h4>Sign up for free and get basic access to the community</h4>
    			<%= link_to "Sign up free", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-default btn-lg btn-block' %>
    		</div>
    	</div>
    	<div class="col-sm-6">
    		<div class="well text-center">
    			<h2 class="text-center">Pro Membership</h2>
    			<h4>Sign up for the pro account for $10/month and get access to the community and contact information</h4>
    			<%= link_to "Sign up pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-default btn-lg btn-block' %>
    		</div>
    	</div>
    </div>

app/views/pages/service.html.erb
<h1>Pages#service</h1>
<p>Find me in app/views/pages/service.html.erb</p>